# Generated by Django 2.2.7 on 2019-11-10 07:09

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20150311_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Şirket Adı'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=markitup.fields.MarkupField(help_text='Markdown formatında yazabilirsiniz.', no_rendered_field=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=255, verbose_name='Başvuru Linki'),
        ),
    ]
