version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.3
  - dependency-name: django
    versions:
    - 3.1.8
  - dependency-name: pytz
    versions:
    - "2021.1"
