# Generated by Django 2.1.2 on 2018-12-18 17:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_description_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
