# Generated by Django 2.1.2 on 2018-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ad ve Soyad')),
                ('email', models.EmailField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Suggestions',
            },
        ),
    ]
