# Generated by Django 2.1.2 on 2018-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20150707_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blog_link',
            field=models.URLField(max_length=255, verbose_name='Blog URL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Gravatar için gerekmektedir, sitede gözükmeyecektir.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub kullanıcı adınızı giriniz.', max_length=255, null=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad ve Soyad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Twitter kullanıcı adınızı giriniz.', max_length=255, null=True, verbose_name='Twitter'),
        ),
    ]
